import 'package:flutter/material.dart';

/// Configuration for the Native WebView Checkout.
class WebViewCheckoutConfig {
  /// The URL generated by your backend using the Fincra API.
  final String checkoutUrl;

  /// An optional redirect URL to intercept successful payments securely.
  final String? redirectUrl;

  /// The background color for the AppBar in the WebView.
  final Color? appBarBackgroundColor;

  /// The title for the AppBar in the WebView.
  final String? appBarTitle;

  /// A widget to show while the WebView is loading.
  final Widget? loadingWidget;

  /// A custom close icon for the AppBar.
  final Widget? closeIcon;

  /// Whether to show a confirmation dialog before cancelling the payment.
  final bool showCancelConfirmationDialog;

  const WebViewCheckoutConfig({
    required this.checkoutUrl,
    this.redirectUrl,
    this.appBarBackgroundColor,
    this.appBarTitle,
    this.loadingWidget,
    this.closeIcon,
    this.showCancelConfirmationDialog = false,
  });
}

/// The bearer of the fees.
enum FeeBearer { business, customer }

/// Defines the available currencies supported by Fincra.
enum FincraCurrency {
  ngn,
  kes,
  ugx,
  ghs,
  zar,
  xaf,
  xof,
}

/// Configuration for the Inline Checkout experience.
class InlineCheckoutConfig {
  /// Your Fincra public key.
  final String publicKey;

  /// The amount to charge the customer.
  final double amount;

  /// The currency to charge the customer in.
  final FincraCurrency currency;

  /// The customer's email address.
  final String customerEmail;

  /// The customer's full name.
  final String customerName;

  /// The customer's phone number.
  final String? customerPhoneNumber;

  /// The unique transaction reference. If not provided, Fincra generates one.
  final String? reference;

  /// Who bears the Fincra processing fees.
  final FeeBearer feeBearer;

  const InlineCheckoutConfig({
    required this.publicKey,
    required this.amount,
    required this.currency,
    required this.customerEmail,
    required this.customerName,
    this.customerPhoneNumber,
    this.reference,
    required this.feeBearer,
  });
}
