import 'package:flutter/material.dart';

/// Configuration for the Native WebView Checkout.
class WebViewCheckoutConfig {
  /// The URL generated by your backend using the Fincra API.
  final String checkoutUrl;

  /// An optional redirect URL to intercept successful payments securely.
  final String? redirectUrl;

  /// The background color for the AppBar in the WebView.
  final Color? appBarBackgroundColor;

  /// The title for the AppBar in the WebView.
  final String? appBarTitle;

  /// A widget to show while the WebView is loading.
  final Widget? loadingWidget;

  /// A custom close icon for the AppBar.
  final Widget? closeIcon;

  /// Whether to show a confirmation dialog before cancelling the payment.
  final bool showCancelConfirmationDialog;

  const WebViewCheckoutConfig({
    required this.checkoutUrl,
    this.redirectUrl,
    this.appBarBackgroundColor,
    this.appBarTitle,
    this.loadingWidget,
    this.closeIcon,
    this.showCancelConfirmationDialog = false,
  });
}

/// The bearer of the fees.
enum FeeBearer { business, customer }

/// Configuration for the Inline JavaScript Checkout.
class InlineCheckoutConfig {
  /// Your Fincra public key.
  final String publicKey;

  /// The amount to be paid.
  final num amount;

  /// The currency for the transaction (e.g., 'NGN').
  final String currency;

  /// The customer's email address.
  final String customerEmail;

  /// The customer's full name.
  final String customerName;

  /// The customer's phone number.
  final String customerPhoneNumber;

  /// An optional custom reference for the transaction.
  final String? reference;

  /// The bearer of the fees ('business' or 'customer').
  final FeeBearer? feeBearer;

  const InlineCheckoutConfig({
    required this.publicKey,
    required this.amount,
    required this.currency,
    required this.customerEmail,
    required this.customerName,
    required this.customerPhoneNumber,
    this.reference,
    this.feeBearer,
  });
}
