import 'package:flutter/material.dart';
import 'models/fincra_response.dart';
import 'models/fincra_error.dart';
import 'models/fincra_checkout_result.dart';
import 'webview/checkout_webview.dart';

class FincraCheckout {
  /// Opens the Fincra checkout in a full-screen WebView.
  ///
  /// The [checkoutUrl] is the URL generated by your backend using the Fincra API.
  /// The optional [redirectUrl] provides a secure way to intercept only your trusted completion URL.
  /// You can customize the app bar via [appBarTitle] and [appBarBackgroundColor].
  ///
  /// Returns a [FincraCheckoutResult] which can be awaited for async flows.
  /// Optionally, you can also provide callbacks for [onSuccess], [onFailed], and [onCancelled].
  static Future<FincraCheckoutResult> open(
    BuildContext context, {
    required String checkoutUrl,
    String? redirectUrl,
    Color? appBarBackgroundColor,
    String? appBarTitle,
    Widget? loadingWidget,
    Widget? closeIcon,
    bool showCancelConfirmationDialog = false,
    ValueChanged<FincraPaymentResponse>? onSuccess,
    ValueChanged<FincraPaymentError>? onFailed,
    VoidCallback? onCancelled,
  }) async {
    final result = await Navigator.of(context).push<FincraCheckoutResult>(
      MaterialPageRoute(
        builder: (context) => CheckoutWebView(
          checkoutUrl: checkoutUrl,
          redirectUrl: redirectUrl,
          appBarBackgroundColor: appBarBackgroundColor,
          appBarTitle: appBarTitle,
          loadingWidget: loadingWidget,
          closeIcon: closeIcon,
          showCancelConfirmationDialog: showCancelConfirmationDialog,
        ),
        fullscreenDialog: true,
      ),
    );

    final finalResult = result ?? FincraCheckoutCancelled();

    if (finalResult is FincraCheckoutSuccess) {
      onSuccess?.call(finalResult.response);
    } else if (finalResult is FincraCheckoutError) {
      onFailed?.call(finalResult.error);
    } else if (finalResult is FincraCheckoutCancelled) {
      onCancelled?.call();
    }

    return finalResult;
  }
}
